-- AlterTable
ALTER TABLE "ParkingLot" ADD COLUMN     "closeAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "description" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "openAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "phone" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "ratings" DOUBLE PRECISION NOT NULL DEFAULT 0;
