services:
  parkNexus-db-postgres:
    image: postgres
    container_name: "parkNexus.db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    restart: always
