-- AlterTable
ALTER TABLE "ParkingLot" ALTER COLUMN "closeAt" DROP DEFAULT,
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "openAt" DROP DEFAULT,
ALTER COLUMN "phone" DROP DEFAULT,
ALTER COLUMN "ratings" DROP DEFAULT;
