/*
  Warnings:

  - The values [TRANSFER_FAILED] on the enum `PAYOUT__ERROR_TYPE_ALIAS` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "PAYOUT__ERROR_TYPE_ALIAS_new" AS ENUM ('INSUFFICIENT_BALANCE', 'CREATE_TRANSFER_FAILED', 'NO_STRIPE_ACCOUNT', 'STRIPE_ACCOUNT_INVALID', 'OTHER');
ALTER TABLE "PayoutRecord" ALTER COLUMN "errorType" TYPE "PAYOUT__ERROR_TYPE_ALIAS_new" USING ("errorType"::text::"PAYOUT__ERROR_TYPE_ALIAS_new");
ALTER TYPE "PAYOUT__ERROR_TYPE_ALIAS" RENAME TO "PAYOUT__ERROR_TYPE_ALIAS_old";
ALTER TYPE "PAYOUT__ERROR_TYPE_ALIAS_new" RENAME TO "PAYOUT__ERROR_TYPE_ALIAS";
DROP TYPE "PAYOUT__ERROR_TYPE_ALIAS_old";
COMMIT;
