/*
  Warnings:

  - The values [CANCELED] on the enum `RESERVATION__STATUS_ALIAS` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "RESERVATION__STATUS_ALIAS_new" AS ENUM ('PENDING', 'ON_GOING', 'CANCELLED', 'OVERSTAYED', 'EXPIRED', 'COMPLETED');
ALTER TABLE "Reservation" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Reservation" ALTER COLUMN "status" TYPE "RESERVATION__STATUS_ALIAS_new" USING ("status"::text::"RESERVATION__STATUS_ALIAS_new");
ALTER TYPE "RESERVATION__STATUS_ALIAS" RENAME TO "RESERVATION__STATUS_ALIAS_old";
ALTER TYPE "RESERVATION__STATUS_ALIAS_new" RENAME TO "RESERVATION__STATUS_ALIAS";
DROP TYPE "RESERVATION__STATUS_ALIAS_old";
ALTER TABLE "Reservation" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;
