export const MAX_ALLOWED_RESERVATIONS = 2;
export const MAX_TIME_ALLOWED_IN_HOURS = 48;
export const EXPIRATION_TIME_IN_HOURS = 1;
export const MAXIMUM_OVERSTAYING_DURATION_IN_HOURS = 1;
export const OVERSTAYING_PENALTY_CHARGES_IN_USD = 50;
export const MINIMUM_BOOKING_DURATION_IN_HOURS = 4;
